### ISSUE TITLE
AddActivity crashes when no internet on open

### ISSUE THREAD

**Issue by strooooke** [lambdasoup/watchlater#65]
Have account, playlist and permissions set up. Go in airplane mode. Launch (example) add screen.

Observe crash due to:
```
    java.lang.RuntimeException: Tea task executor threw exception
        at com.lambdasoup.tea.Tea$runBg$1$2.invoke(Tea.kt:81)
        at com.lambdasoup.tea.Tea$runBg$1$2.invoke(Tea.kt:80)
        at com.lambdasoup.tea.Tea$DefaultEngine.post$lambda-2$lambda-1(Tea.kt:137)
        at com.lambdasoup.tea.Tea$DefaultEngine.$r8$lambda$D5grVRbrpz6uzL7Zldln94I-EHs(Unknown Source:0)
        at com.lambdasoup.tea.Tea$DefaultEngine$$ExternalSyntheticLambda1.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:942)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.RuntimeException: could not get token
        at com.lambdasoup.watchlater.data.AccountRepository.getAuthToken(AccountRepository.kt:94)
        at com.lambdasoup.watchlater.viewmodel.AddViewModel$getAuthToken$1.invoke(AddViewModel.kt:54)
        at com.lambdasoup.watchlater.viewmodel.AddViewModel$getAuthToken$1.invoke(AddViewModel.kt:53)
        at com.lambdasoup.tea.Cmd$Companion$task$1$1.invoke(Cmd.kt:51)
        at com.lambdasoup.tea.Tea$runBg$1.invoke(Tea.kt:75)
        at com.lambdasoup.tea.Tea$runBg$1.invoke(Tea.kt:73)
        at com.lambdasoup.tea.Tea$DefaultEngine.execute$lambda-0(Tea.kt:136)
        at com.lambdasoup.tea.Tea$DefaultEngine.$r8$lambda$10Qi51QdNYyh2l4FRDX_Qwxlrbw(Unknown Source:0)
        at com.lambdasoup.tea.Tea$DefaultEngine$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
     Caused by: java.io.IOException: NetworkError
        at android.accounts.AccountManager.convertErrorToException(AccountManager.java:2628)
        at android.accounts.AccountManager.-$$Nest$mconvertErrorToException(Unknown Source:0)
        at android.accounts.AccountManager$AmsTask$Response.onError(AccountManager.java:2479)
        at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:107)
        at android.os.Binder.execTransactInternal(Binder.java:1285)
        at android.os.Binder.execTransact(Binder.java:1244)
```

**Comment by strooooke** [comment]
Not on API level 25, but on 33.
